// HostProfile interface and hosts array for all hosts in properties, experiences, and services
export interface HostProfile {
  id: string;
  name: string;
  email: string;
  propertyIds?: string[];
  experienceIds?: string[];
  serviceIds?: string[];
}

// This file should be generated by aggregating all unique hosts from mockProperties, mockExperiences, and mockServices.
// For now, here is a static example. You should update this with real aggregation logic or a script if needed.

export const hosts: HostProfile[] = [
  {
    id: 'emmanuel',
    name: 'Emmanuel',
    email: 'emmanuel@example.com',
    propertyIds: ['prop001'],
    experienceIds: ['exp101'],
  },
  {
    id: 'ama',
    name: 'Ama',
    email: 'ama@example.com',
    propertyIds: ['prop002'],
    experienceIds: ['exp102'],
  },
  {
    id: 'kwame',
    name: 'Kwame',
    email: 'kwame@example.com',
    propertyIds: ['prop003'],
    experienceIds: ['exp103'],
  },
  {
    id: 'linda',
    name: 'Linda',
    email: 'linda@example.com',
    propertyIds: ['prop004'],
    experienceIds: ['exp104'],
  },
  {
    id: 'kojo',
    name: 'Kojo',
    email: 'kojo@example.com',
    propertyIds: ['prop005'],
    experienceIds: ['exp105'],
  },
  {
    id: 'akosua',
    name: 'Akosua',
    email: 'akosua@example.com',
    propertyIds: ['prop006'],
    experienceIds: ['exp106'],
  },
  {
    id: 'yaw',
    name: 'Yaw',
    email: 'yaw@example.com',
    propertyIds: ['prop007'],
    experienceIds: ['exp107'],
  },
  {
    id: 'efua',
    name: 'Efua',
    email: 'efua@example.com',
    propertyIds: ['prop008'],
    experienceIds: ['exp108'],
  },
  {
    id: 'nana',
    name: 'Nana',
    email: 'nana@example.com',
    propertyIds: ['prop009'],
    experienceIds: ['exp109'],
    serviceIds: ['svc108'],
  },
  {
    id: 'kofi',
    name: 'Kofi',
    email: 'kofi@example.com',
    propertyIds: ['prop010'],
    experienceIds: ['exp110'],
    serviceIds: ['svc105'],
  },
  {
    id: 'abena',
    name: 'Abena',
    email: 'abena@example.com',
    propertyIds: ['prop011'],
    experienceIds: ['exp111'],
    serviceIds: ['svc106'],
  },
  {
    id: 'esi',
    name: 'Esi',
    email: 'esi@example.com',
    propertyIds: ['prop012'],
    experienceIds: ['exp112'],
    serviceIds: ['svc107'],
  },
  {
    id: 'mensah',
    name: 'Mensah',
    email: 'mensah@example.com',
    propertyIds: ['prop013'],
    serviceIds: ['svc102'],
  },
  {
    id: 'adwoa',
    name: 'Adwoa',
    email: 'adwoa@example.com',
    propertyIds: ['prop014'],
    serviceIds: ['svc104'],
  },
  {
    id: 'selorm',
    name: 'Selorm',
    email: 'selorm@example.com',
    propertyIds: ['prop015'],
    serviceIds: ['svc104'],
  },
  {
    id: 'asante',
    name: 'Asante',
    email: 'asante@example.com',
    serviceIds: ['svc101'],
  },
  {
    id: 'akua',
    name: 'Akua',
    email: 'akua@example.com',
    serviceIds: ['svc103'],
  },
]; 